routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ManagerController;
use App\Http\Controllers\Admin\MemberController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductVariantController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\NotificationController;
use App\Http\Middleware\AuthLoginAdmin;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', [AuthController::class, 'getViewLogin'])->name('login-page')->middleware('authCheckManagerLogout');
Route::post('/login-admin', [AuthController::class, 'doLoginAdmin'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware([AuthLoginAdmin::class])->group(function () {
    /**
     * Route home
     */
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('order', [OrderController::class, 'index'])->name('orders.index');
    Route::get('member', [MemberController::class, 'index'])->name('member.index');

    Route::get('notifications/{notification}/mark-as-read', [NotificationController::class, 'markAtRead']);

    /**
     * Route slide
     */
    Route::group(['prefix' => 'slide', 'middleware' => 'policyOfStaff'], function() {
        Route::get('/', [SlideController::class, 'index'])->name('slides.index');
        Route::get('create', [SlideController::class, 'create'])->name('slides.form_create');
        Route::post('/create', [SlideController::class, 'store'])->name('slides.create');
        Route::get('/edit/{id}', [SlideController::class, 'edit'])->name('slides.edit');
        Route::put('/update/{id}', [SlideController::class, 'update'])->name('slides.update');
        Route::get('/delete/{id}', [SlideController::class, 'destroy'])->name('slides.delete');
    });
    /**
     * Route category
     */
    Route::resource('categories', CategoryController::class)->except(['show'])->middleware('policyOfStaff');
    /**
     * Route product
     */
    Route::prefix('product')->group(function() {
        Route::get('/', [ProductController::class, 'index'])->name('products.index');
        Route::get('/create', [ProductController::class, 'create'])->name('products.form_create')->middleware('policyOfStaff');
        Route::post('/create', [ProductController::class, 'store'])->name('products.create')->middleware('policyOfStaff');
        Route::get('/view/{id}', [ProductController::class, 'show'])->name('products.show');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('products.edit')->middleware('policyOfStaff');
        Route::put('/update/{id}', [ProductController::class, 'update'])->name('products.update')->middleware('policyOfStaff');
        Route::get('/delete/{id}', [ProductController::class, 'destroy'])->name('products.delete')->middleware('policyOfStaff');

        Route::resource('attributes', AttributeController::class)->only(['store', 'update', 'destroy'])->middleware('policyOfStaff');
        Route::group(['prefix' => 'variants', 'middleware' => 'policyOfStaff'], function() {
            Route::get('/{product}', [ProductVariantController::class, 'getVariantsOfProduct'])->name('products.variants');
            Route::put('/{product}', [ProductVariantController::class, 'updateProductVariants'])->name('products.variants.update');
        });
    });
    /**
     * Route manager
     */
    Route::group(['prefix' => 'manager', 'middleware' => 'policyOfStaff'], function() {
        Route::get('/', [ManagerController::class, 'index'])->name('manager.index');
        Route::get('/edit/{id}', [ManagerController::class, 'getFormEdit'])->name('managers.edit');
        Route::put('/update/{id}', [ManagerController::class, 'update'])->name('managers.update');
        Route::post('/create', [ManagerController::class, 'store'])->name('managers.create');
        Route::get('/create', [ManagerController::class, 'create'])->name('managers.form_create');
        Route::get('/delete/{id}', [ManagerController::class, 'destroy'])->middleware('policyOfManager')->name('managers.delete');
    });

    Route::prefix('orders')->group(function () {
        Route::get('', [OrderController::class, 'index'])->name('orders.index');
        Route::get('/{order}', [OrderController::class, 'detail'])->name('orders.detail');
        Route::get('/{order}/update-status', [OrderController::class, 'updateStatus'])->name('orders.update-status');
    });
});
// Route::get('test', function () {
//    return Hash::make(123456);
// });

routes/user.php
<?php

use App\Http\Controllers\NotificationController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\ProductController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\PaymentController;
use App\Http\Controllers\User\AuthController;
use App\Http\Controllers\User\ProfileController;
use Symfony\Component\HttpKernel\Profiler\Profile;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('dang-nhap', [AuthController::class, 'signIn'])->name('auth.sign-in')
    ->middleware('authCheckMemberLogout');
Route::post('login', [AuthController::class, 'doLogin'])->name('auth.login')
    ->middleware('authCheckMemberLogout');
Route::get('dang-ky', [AuthController::class, 'signUp'])->name('auth.sign-up')
    ->middleware('authCheckMemberLogout');
Route::post('register', [AuthController::class, 'doRegister'])->name('auth.register')
    ->middleware('authCheckMemberLogout');
Route::get('dang-xuat', [AuthController::class, 'logout'])->name('auth.logout');

Route::get('', function () {
    return redirect()->route('home');
});

Route::get('trang-chu', [HomeController::class, 'index'])->name('home');
Route::prefix('san-pham')->group(function () {
    Route::get('', [ProductController::class, 'index'])->name('products.index');
    Route::get('/{slug}', [ProductController::class, 'getItemBySlug'])->name('products.slug');
});
Route::post('product/get-variant-price', [ProductController::class, 'getVariantPrice']);
Route::get('gio-hang', [CartController::class, 'index'])->name('cart.index');
Route::post('cart/add/{slug}', [CartController::class, 'add'])->name('cart.add');
Route::get('cart/remove/{rowId}', [CartController::class, 'remove'])->name('cart.remove');
Route::put('cart/update', [CartController::class, 'update'])->name('cart.update');
Route::get('thanh-toan', [PaymentController::class, 'index'])->name('payment.index');
Route::post('payment', [PaymentController::class, 'handlePayment'])->name('payment.handle');
Route::get('ho-so', [ProfileController::class, 'getProfileUser'])->name('profile');
Route::put('ho-so/cap-nhat/{id}', [ProfileController::class, 'updateProfile'])->name('profile.update');
Route::get('don-mua', [ProfileController::class, 'getViewOrder'])->name('profile.order');
Route::get('orders/{order}/update', [ProfileController::class, 'updateOrders'])->name('profile.order.update');
Route::get('thong-bao', [ProfileController::class, 'getViewNotifications'])->name('profile.notification');
Route::get('notifications/{notification}/mark-as-read', [NotificationController::class, 'markAtRead']);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = "products";
    protected $fillable = [
        'category_id',
        'name',
        'slug',
        'code',
        'feature_image',
        'summary',
        'detail',
        'description',
        'status'
    ];

    protected static function booted()
    {
        parent::booted();
        static::creating(function ($product) {
            $product->slug = Str::slug($product->name) . '-prod' . $product->id . '.' . Str::random(10) . '.' . time();
        });
        static::updating(function ($product) {
            $product->slug = Str::slug($product->name) . '-prod' . $product->id . '.' . Str::random(10) . '.' . time();
        });
    }

    public function getFeatureImagePathAttribute()
    {
        return asset("storage/images/products/{$this->feature_image}");
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function attributes()
    {
        return $this->belongsToMany(AttributeValue::class, 'attribute_product', 'product_id', 'attribute_value_id');
    }

    public function variants()
    {
        return $this->hasMany(ProductVariant::class, 'product_id', 'id');
    }

    public function images()
    {
        return $this->hasMany(ProductImage::class, 'product_id', 'id');
    }

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Repositories\AttributeRepository;
use App\Repositories\AttributeValueRepository;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    protected $productService;
    protected $categoryService;
    protected $attributeRepository;
    protected $attributeValueRepo;

    public function __construct(
        ProductService $productService,
        CategoryService $categoryService,
        AttributeRepository $attributeRepository,
        AttributeValueRepository $attributeValueRepo
    ) {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
        $this->attributeRepository = $attributeRepository;
        $this->attributeValueRepo = $attributeValueRepo;
    }

    public function index() {
        $products = $this->productService->getAll();
        return view('admin.product.index', compact('products'));
    }

    public function create()
    {
        $categories = $this->categoryService->getAll();
        $attributes = $this->attributeRepository->all();
        $attributeValues = $this->attributeValueRepo->getAttributeValues();
        return view('admin.product.insert', compact('categories', 'attributes', 'attributeValues'));
    }

    public function store(StoreProductRequest $request)
    {
        $response = $this->productService->store($request);
        if ($response['success']) {
            $product = $response['data']['product'];
            return redirect()->route('admin.products.variants', ['product' => $product->id])->with('success_msg', $response['message']);
        }
        return redirect()->back()->with('error_msg', $response['message'])->withInput();

    }

    public function show(int $id)
    {
        $product = $this->productService->getById($id);
        return view('admin.product.view', compact('product'));
    }

    public function edit(int $id)
    {
        $categories = $this->categoryService->getAll();
        $product = $this->productService->getById($id);
        $attributes = $this->attributeRepository->all();
        $attributeValues = $this->attributeValueRepo->getAttributeValues();
        return view('admin.product.edit', compact('product', 'categories', 'attributes', 'attributeValues'));
    }

    public function update(int $id, UpdateProductRequest $request)
    {
        $response = $this->productService->update($id, $request);
        if ($response['success']) {
            return redirect()->back()->with('success_msg', $response['message']);
        }
        return redirect()->back()->with('error_msg', $response['message']);
    }

    public function destroy(int $id)
    {
        $response = $this->productService->delete($id);
        if ($response['success']) {
            return redirect()->back()->with('success_msg', $response['message']);
        }
        return redirect()->back()->with('error_msg', $response['message']);
    }
}

app/Http/Controllers/User/ProductController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Repositories\CategoryRepository;
use App\Repositories\ProductRepository;
use App\Services\ProductService;
use App\Services\ProductVariantService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    protected $productRepository;
    protected $categoryRepository;
    protected $productService;
    protected $productVariantService;

    public function __construct(
        ProductRepository $productRepository,
        CategoryRepository $categoryRepository,
        ProductService $productService,
        ProductVariantService $productVariantService
    ) {
        $this->productRepository = $productRepository;
        $this->categoryRepository = $categoryRepository;
        $this->productService = $productService;
        $this->productVariantService = $productVariantService;
    }

    public function index(Request $request)
    {
        $products = $this->productRepository->getProductsPaginate($request, 24);
        return view('user.products.list.index', compact('products'));
    }

    public function getItemBySlug($slug)
    {
        if (Str::contains($slug, '-cat')) {
            $category = $this->categoryRepository->getCategoryBySlug($slug);
            $products = $category->products()->orderBy('id', 'DESC')->paginate(24);
            return view('user.products.list.index', compact('category', 'products', 'slug'));
        }
        if (Str::contains($slug, '-prod')) {
            $products = $this->productService->getProductInterested($limit = 4);
            $response = $this->productService->handleProductBySlug($slug);
            return view('user.products.detail.index', [
                'product' => $response['product'],
                'minPrice' => $response['minPrice'],
                'maxPrice' => $response['maxPrice'],
                'totalAmountProduct' => $response['totalAmountProduct'],
                'productAttributes' => $response['productAttributes'],
                'attrValues' => $response['attrValues'],
                'products' => $products
            ]);
        }
    }

    public function getVariantPrice(Request $request)
    {
        $response = $this->productVariantService->handleVariantPrice($request->all());
        return response()->json($response);
    }
}

resources/views/admin/product/components/attribute-modal-update.blade.php
<!-- Modal -->
<div class="modal fade" id="attributeModalUpdate" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form class="attr-form" action="" method="post">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <div class="form-group">
                        <label>Tên thuộc tính <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="attr_name" placeholder="Nhập tên thuộc tính" value="">
                    </div>
                    <div class="form-group attr-group">
                        <label>Giá trị thuộc tính <span class="text-danger">*</span></label>
                        <button type="button" class="btn btn-default btn-sm btn-add-attr-values">
                            Thêm giá trị thuộc tính <i class="fas fa-plus-circle"></i>
                        </button>
                        <div class="attr-value-group"></div>
                        <input type="hidden" name="attribute_values_delete" value="">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/product/components/attribute-modal.blade.php
<!-- Modal -->
<div class="modal fade" id="attributeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form class="attr-form" action="{{ route('admin.attributes.store') }}" method="post">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Thêm thuộc tính</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Tên thuộc tính <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="attr_name" placeholder="Nhập tên thuộc tính" value="{{ old('attr_name') }}">
                    </div>
                    <div class="form-group attr-group">
                        <label>Giá trị thuộc tính <span class="text-danger">*</span></label>
                        <button type="button" class="btn btn-default btn-sm btn-add-attr-values">
                            Thêm giá trị thuộc tính <i class="fas fa-plus-circle"></i>
                        </button>
                        <div class="input-group mb-2 attr-value-input-group">
                            <input type="text" class="form-control attr-value-input" name="attribute_values[]" placeholder="Nhập giá trị thuộc tính">
                            <div class="input-group-append">
                                <button class="btn btn-outline-danger btn-sm btn-delete-option" type="button">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/product/components/list-attributes.blade.php
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Danh sách thuộc tính sản phẩm</h3>
      </div>
    <div class="card-body">
        <button type="button" data-toggle="modal" data-target="#attributeModal" class="btn btn-primary btn-sm mb-2">
            <span class="glyphicon glyphicon-floppy-save"></span>
            Thêm thuộc tính
        </button>
        @if (session()->has('failed_validate'))
            <div class="alert alert-danger">
                <strong>{{ session('failed_validate') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div id="table-responsive1" class="table-responsive">
            <table id="attribute-list" class="table table-hover table-bordered table-content">
                <thead>
                    <tr>
                        <th>Tên thuộc tính</th>
                        <th>Giá trị thuộc tính</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody class="attr-content">
                    @if ($attributes->isNotEmpty())
                        @foreach ($attributes as $attr)
                            <tr>
                                <td>
                                    {{ $attr->name }}
                                </td>
                                <td>
                                    @foreach ($attr->attributeValues as $key => $attrValue)
                                        @if ($key == count($attr->attributeValues) - 1)
                                            <span>{{ $attrValue->name }}</span>
                                        @else
                                            <span>{{ $attrValue->name }},</span>
                                        @endif
                                    @endforeach
                                </td>
                                <td>
                                    <button type="button" class="btn btn-warning btn-xs btn-edit-attr" data-attr="{{ $attr }}">Sửa</button>
                                    {{-- <form class="d-inline-block" action="{{ route('admin.attributes.destroy', ['attribute' => $attr->id]) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="button" class="btn btn-danger btn-xs btn-delete-attr">Xóa</button>
                                    </form> --}}
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="3">
                                <h4 class="text-center">Chưa có thuộc tính sản phẩm</h4>
                            </td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
</div>