routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ManagerController;
use App\Http\Controllers\Admin\MemberController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductVariantController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\NotificationController;
use App\Http\Middleware\AuthLoginAdmin;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', [AuthController::class, 'getViewLogin'])->name('login-page')->middleware('authCheckManagerLogout');
Route::post('/login-admin', [AuthController::class, 'doLoginAdmin'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware([AuthLoginAdmin::class])->group(function () {
    /**
     * Route home
     */
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('order', [OrderController::class, 'index'])->name('orders.index');
    Route::get('member', [MemberController::class, 'index'])->name('member.index');

    Route::get('notifications/{notification}/mark-as-read', [NotificationController::class, 'markAtRead']);

    /**
     * Route slide
     */
    Route::group(['prefix' => 'slide', 'middleware' => 'policyOfStaff'], function() {
        Route::get('/', [SlideController::class, 'index'])->name('slides.index');
        Route::get('create', [SlideController::class, 'create'])->name('slides.form_create');
        Route::post('/create', [SlideController::class, 'store'])->name('slides.create');
        Route::get('/edit/{id}', [SlideController::class, 'edit'])->name('slides.edit');
        Route::put('/update/{id}', [SlideController::class, 'update'])->name('slides.update');
        Route::get('/delete/{id}', [SlideController::class, 'destroy'])->name('slides.delete');
    });
    /**
     * Route category
     */
    Route::resource('categories', CategoryController::class)->except(['show'])->middleware('policyOfStaff');
    /**
     * Route product
     */
    Route::prefix('product')->group(function() {
        Route::get('/', [ProductController::class, 'index'])->name('products.index');
        Route::get('/create', [ProductController::class, 'create'])->name('products.form_create')->middleware('policyOfStaff');
        Route::post('/create', [ProductController::class, 'store'])->name('products.create')->middleware('policyOfStaff');
        Route::get('/view/{id}', [ProductController::class, 'show'])->name('products.show');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('products.edit')->middleware('policyOfStaff');
        Route::put('/update/{id}', [ProductController::class, 'update'])->name('products.update')->middleware('policyOfStaff');
        Route::get('/delete/{id}', [ProductController::class, 'destroy'])->name('products.delete')->middleware('policyOfStaff');

        Route::resource('attributes', AttributeController::class)->only(['store', 'update', 'destroy'])->middleware('policyOfStaff');
        Route::group(['prefix' => 'variants', 'middleware' => 'policyOfStaff'], function() {
            Route::get('/{product}', [ProductVariantController::class, 'getVariantsOfProduct'])->name('products.variants');
            Route::put('/{product}', [ProductVariantController::class, 'updateProductVariants'])->name('products.variants.update');
        });
    });
    /**
     * Route manager
     */
    Route::group(['prefix' => 'manager', 'middleware' => 'policyOfStaff'], function() {
        Route::get('/', [ManagerController::class, 'index'])->name('manager.index');
        Route::get('/edit/{id}', [ManagerController::class, 'getFormEdit'])->name('managers.edit');
        Route::put('/update/{id}', [ManagerController::class, 'update'])->name('managers.update');
        Route::post('/create', [ManagerController::class, 'store'])->name('managers.create');
        Route::get('/create', [ManagerController::class, 'create'])->name('managers.form_create');
        Route::get('/delete/{id}', [ManagerController::class, 'destroy'])->middleware('policyOfManager')->name('managers.delete');
    });

    Route::prefix('orders')->group(function () {
        Route::get('', [OrderController::class, 'index'])->name('orders.index');
        Route::get('/{order}', [OrderController::class, 'detail'])->name('orders.detail');
        Route::get('/{order}/update-status', [OrderController::class, 'updateStatus'])->name('orders.update-status');
    });
});
// Route::get('test', function () {
//    return Hash::make(123456);
// });

routes/user.php
<?php

use App\Http\Controllers\NotificationController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\ProductController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\PaymentController;
use App\Http\Controllers\User\AuthController;
use App\Http\Controllers\User\ProfileController;
use Symfony\Component\HttpKernel\Profiler\Profile;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('dang-nhap', [AuthController::class, 'signIn'])->name('auth.sign-in')
    ->middleware('authCheckMemberLogout');
Route::post('login', [AuthController::class, 'doLogin'])->name('auth.login')
    ->middleware('authCheckMemberLogout');
Route::get('dang-ky', [AuthController::class, 'signUp'])->name('auth.sign-up')
    ->middleware('authCheckMemberLogout');
Route::post('register', [AuthController::class, 'doRegister'])->name('auth.register')
    ->middleware('authCheckMemberLogout');
Route::get('dang-xuat', [AuthController::class, 'logout'])->name('auth.logout');

Route::get('', function () {
    return redirect()->route('home');
});

Route::get('trang-chu', [HomeController::class, 'index'])->name('home');
Route::prefix('san-pham')->group(function () {
    Route::get('', [ProductController::class, 'index'])->name('products.index');
    Route::get('/{slug}', [ProductController::class, 'getItemBySlug'])->name('products.slug');
});
Route::post('product/get-variant-price', [ProductController::class, 'getVariantPrice']);
Route::get('gio-hang', [CartController::class, 'index'])->name('cart.index');
Route::post('cart/add/{slug}', [CartController::class, 'add'])->name('cart.add');
Route::get('cart/remove/{rowId}', [CartController::class, 'remove'])->name('cart.remove');
Route::put('cart/update', [CartController::class, 'update'])->name('cart.update');
Route::get('thanh-toan', [PaymentController::class, 'index'])->name('payment.index');
Route::post('payment', [PaymentController::class, 'handlePayment'])->name('payment.handle');
Route::get('ho-so', [ProfileController::class, 'getProfileUser'])->name('profile');
Route::put('ho-so/cap-nhat/{id}', [ProfileController::class, 'updateProfile'])->name('profile.update');
Route::get('don-mua', [ProfileController::class, 'getViewOrder'])->name('profile.order');
Route::get('orders/{order}/update', [ProfileController::class, 'updateOrders'])->name('profile.order.update');
Route::get('thong-bao', [ProfileController::class, 'getViewNotifications'])->name('profile.notification');
Route::get('notifications/{notification}/mark-as-read', [NotificationController::class, 'markAtRead']);

resources/views/admin/layouts/components/footer.blade.php
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.1.0
    </div>
</footer>

resources/views/admin/layouts/components/header.blade.php
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Liên hệ</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        {{-- <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
            <form class="form-inline">
                <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                    </button>
                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                    <i class="fas fa-times"></i>
                    </button>
                </div>
                </div>
            </form>
            </div>
        </li> --}}
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown admin-notify-section">
            <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-bell"></i>
            @if ($unreadAdminNoti->count())
            <span class="badge badge-warning navbar-badge">{{ $unreadAdminNoti->count() }}</span>
            @endif
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <span class="dropdown-item dropdown-header">{{ $unreadAdminNoti->count() }} Thông báo chưa đọc</span>
            <div class="dropdown-divider"></div>
            <div class="dropdown-divider"></div>
            @foreach ($adminNoti as $noti)
            <a data-link="{{ $noti->link }}" data-noti-id="{{ $noti->id }}" class="read-at dropdown-item py-2 px-2 @empty($noti->read_at) bg-info @endempty" style="cursor: pointer;">
                <div class="row">
                    <div class="col-2">
                        <i class="fas fa-users mr-2"></i>
                    </div>
                    <div class="col-10">
                        <p class="text-sm">{{ $noti->message }}</p>
                        <p class="text-dark text-xs">{{ $noti->time }}</p>
                    </div>
                </div>
            </a>
            <div class="dropdown-divider"></div>
            @endforeach
            {{-- <a href="#" class="dropdown-item">
                <i class="fas fa-file mr-2"></i> 3 new reports
                <span class="float-right text-muted text-sm">2 days</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div> --}}
        </li>
        <div class="dropdown">
            <a class="dropdown-toggle d-block p-2" style="color: white" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{getLoggedInUser()->email}}
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{{ route('admin.logout') }}">Đăng xuất</a>
            </div>
        </div>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" role="button">
            <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
  </nav>

resources/views/admin/layouts/components/script.blade.php
<!-- jQuery -->
<script src="{{ asset('adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('adminlte/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
@yield('custom-script')
<!-- AdminLTE App -->
<script src="{{ asset('adminlte/dist/js/adminlte.min.js') }}"></script>
{{-- <!-- AdminLTE for demo purposes -->
<script src="{{ asset('adminlte/dist/js/demo.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('adminlte/dist/js/pages/dashboard.js') }}"></script> --}}
<script src="//cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
<script src="{{ asset('admin/script.js') }}"></script>
@yield('my-script')

resources/views/admin/layouts/components/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{ asset('adminlte/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ isManagerLogged() ? getLoggedInUser()->name : 'Admin' }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="{{ route('admin.dashboard.index') }}" class="nav-link @yield('active-dashboard')">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Bảng Điều Khiển
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('admin.products.index') }}" class="nav-link @yield('active-products')">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Quản Lý Sản Phẩm
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('admin.categories.index') }}" class="nav-link @yield('active-categories')">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Danh Mục Sản Phẩm
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('admin.orders.index') }}" class="nav-link @yield('active-orders')">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Quản Lý Đơn Hàng
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('admin.member.index') }}" class="nav-link @yield('active-members')">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Danh Sách Thành Viên
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('admin.manager.index') }}" class="nav-link @yield('active-manager')">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Quản Lý Nhân Viên
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('admin.slides.index') }}" class="nav-link @yield('active-slide')">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Quản Lý Slide
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

resources/views/admin/layouts/components/stylesheet.blade.php
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
{{-- <!-- iCheck -->
<link rel="stylesheet" href="{{ asset('adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}"> --}}
@yield('custom-css')
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('adminlte/dist/css/adminlte.min.css') }}">
{{-- <!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('adminlte/plugins/daterangepicker/daterangepicker.css') }}"> --}}
@yield('my-css')