routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ManagerController;
use App\Http\Controllers\Admin\MemberController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductVariantController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\NotificationController;
use App\Http\Middleware\AuthLoginAdmin;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', [AuthController::class, 'getViewLogin'])->name('login-page')->middleware('authCheckManagerLogout');
Route::post('/login-admin', [AuthController::class, 'doLoginAdmin'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware([AuthLoginAdmin::class])->group(function () {
    /**
     * Route home
     */
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('order', [OrderController::class, 'index'])->name('orders.index');
    Route::get('member', [MemberController::class, 'index'])->name('member.index');

    Route::get('notifications/{notification}/mark-as-read', [NotificationController::class, 'markAtRead']);

    /**
     * Route slide
     */
    Route::group(['prefix' => 'slide', 'middleware' => 'policyOfStaff'], function() {
        Route::get('/', [SlideController::class, 'index'])->name('slides.index');
        Route::get('create', [SlideController::class, 'create'])->name('slides.form_create');
        Route::post('/create', [SlideController::class, 'store'])->name('slides.create');
        Route::get('/edit/{id}', [SlideController::class, 'edit'])->name('slides.edit');
        Route::put('/update/{id}', [SlideController::class, 'update'])->name('slides.update');
        Route::get('/delete/{id}', [SlideController::class, 'destroy'])->name('slides.delete');
    });
    /**
     * Route category
     */
    Route::resource('categories', CategoryController::class)->except(['show'])->middleware('policyOfStaff');
    /**
     * Route product
     */
    Route::prefix('product')->group(function() {
        Route::get('/', [ProductController::class, 'index'])->name('products.index');
        Route::get('/create', [ProductController::class, 'create'])->name('products.form_create')->middleware('policyOfStaff');
        Route::post('/create', [ProductController::class, 'store'])->name('products.create')->middleware('policyOfStaff');
        Route::get('/view/{id}', [ProductController::class, 'show'])->name('products.show');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('products.edit')->middleware('policyOfStaff');
        Route::put('/update/{id}', [ProductController::class, 'update'])->name('products.update')->middleware('policyOfStaff');
        Route::get('/delete/{id}', [ProductController::class, 'destroy'])->name('products.delete')->middleware('policyOfStaff');

        Route::resource('attributes', AttributeController::class)->only(['store', 'update', 'destroy'])->middleware('policyOfStaff');
        Route::group(['prefix' => 'variants', 'middleware' => 'policyOfStaff'], function() {
            Route::get('/{product}', [ProductVariantController::class, 'getVariantsOfProduct'])->name('products.variants');
            Route::put('/{product}', [ProductVariantController::class, 'updateProductVariants'])->name('products.variants.update');
        });
    });
    /**
     * Route manager
     */
    Route::group(['prefix' => 'manager', 'middleware' => 'policyOfStaff'], function() {
        Route::get('/', [ManagerController::class, 'index'])->name('manager.index');
        Route::get('/edit/{id}', [ManagerController::class, 'getFormEdit'])->name('managers.edit');
        Route::put('/update/{id}', [ManagerController::class, 'update'])->name('managers.update');
        Route::post('/create', [ManagerController::class, 'store'])->name('managers.create');
        Route::get('/create', [ManagerController::class, 'create'])->name('managers.form_create');
        Route::get('/delete/{id}', [ManagerController::class, 'destroy'])->middleware('policyOfManager')->name('managers.delete');
    });

    Route::prefix('orders')->group(function () {
        Route::get('', [OrderController::class, 'index'])->name('orders.index');
        Route::get('/{order}', [OrderController::class, 'detail'])->name('orders.detail');
        Route::get('/{order}/update-status', [OrderController::class, 'updateStatus'])->name('orders.update-status');
    });
});
// Route::get('test', function () {
//    return Hash::make(123456);
// });

routes/user.php
<?php

use App\Http\Controllers\NotificationController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\ProductController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\PaymentController;
use App\Http\Controllers\User\AuthController;
use App\Http\Controllers\User\ProfileController;
use Symfony\Component\HttpKernel\Profiler\Profile;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('dang-nhap', [AuthController::class, 'signIn'])->name('auth.sign-in')
    ->middleware('authCheckMemberLogout');
Route::post('login', [AuthController::class, 'doLogin'])->name('auth.login')
    ->middleware('authCheckMemberLogout');
Route::get('dang-ky', [AuthController::class, 'signUp'])->name('auth.sign-up')
    ->middleware('authCheckMemberLogout');
Route::post('register', [AuthController::class, 'doRegister'])->name('auth.register')
    ->middleware('authCheckMemberLogout');
Route::get('dang-xuat', [AuthController::class, 'logout'])->name('auth.logout');

Route::get('', function () {
    return redirect()->route('home');
});

Route::get('trang-chu', [HomeController::class, 'index'])->name('home');
Route::prefix('san-pham')->group(function () {
    Route::get('', [ProductController::class, 'index'])->name('products.index');
    Route::get('/{slug}', [ProductController::class, 'getItemBySlug'])->name('products.slug');
});
Route::post('product/get-variant-price', [ProductController::class, 'getVariantPrice']);
Route::get('gio-hang', [CartController::class, 'index'])->name('cart.index');
Route::post('cart/add/{slug}', [CartController::class, 'add'])->name('cart.add');
Route::get('cart/remove/{rowId}', [CartController::class, 'remove'])->name('cart.remove');
Route::put('cart/update', [CartController::class, 'update'])->name('cart.update');
Route::get('thanh-toan', [PaymentController::class, 'index'])->name('payment.index');
Route::post('payment', [PaymentController::class, 'handlePayment'])->name('payment.handle');
Route::get('ho-so', [ProfileController::class, 'getProfileUser'])->name('profile');
Route::put('ho-so/cap-nhat/{id}', [ProfileController::class, 'updateProfile'])->name('profile.update');
Route::get('don-mua', [ProfileController::class, 'getViewOrder'])->name('profile.order');
Route::get('orders/{order}/update', [ProfileController::class, 'updateOrders'])->name('profile.order.update');
Route::get('thong-bao', [ProfileController::class, 'getViewNotifications'])->name('profile.notification');
Route::get('notifications/{notification}/mark-as-read', [NotificationController::class, 'markAtRead']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = "categories";
    protected $fillable = [
        'name',
        'slug',
        'image',
        'description',
        'parent'
    ];

    protected static function booted()
    {
        parent::booted();
        static::creating(function ($category) {
            $category->slug = Str::slug($category->name) . '-cat' . $category->id . '.' . time();
        });
        static::updating(function ($category) {
            $category->slug = Str::slug($category->name) . '-cat' . $category->id . '.' . time();
        });
    }

    public function getNameAttribute($value)
    {
        return Str::ucfirst($value);
    }

    public function getImagePathAttribute()
    {
        return asset("storage/images/categories/{$this->image}");
    }

    public function products()
    {
        return $this->hasMany(Product::class, 'category_id', 'id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Models\Category;
use App\Repositories\CategoryRepository;
use App\Services\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryService;
    protected $categoryRepository;

    public function __construct(CategoryService $categoryService, CategoryRepository $categoryRepository)
    {
        $this->categoryService = $categoryService;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryRepository->all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        $execResponse = $this->categoryService->handle($request);
        if ($execResponse['success']) {
            return redirect()->route('admin.categories.index')->with('success_msg', $execResponse['message']);
        }
        return redirect()->back()->with('error_msg', $execResponse['message'])->withInput();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $execResponse = $this->categoryService->handle($request, $category);
        if ($execResponse['success']) {
            return redirect()->route('admin.categories.index')->with('success_msg', $execResponse['message']);
        }
        return redirect()->back()->with('error_msg', $execResponse['message'])->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $execResponse = $this->categoryService->delete($category);
        if ($execResponse['success']) {
            return redirect()->back()->with('success_msg', $execResponse['message']);
        }
        return redirect()->back()->with('error_msg', $execResponse['message']);
    }
}

resources/views/admin/categories/_form.blade.php
<form action="{{ empty($category) ? route('admin.categories.store') : route('admin.categories.update', ['category' => $category->id]) }}" method="post" enctype="multipart/form-data" accept-charset="utf-8">
    @if (!empty($category))
        @method('PUT')
    @endif
    @csrf
    <section class="content-header">
        <div class="breadcrumb">
            <button type="submit" class="btn btn-primary btn-sm mr-3">
                <span class="glyphicon glyphicon-floppy-save"></span>
                Lưu[Thêm]
            </button>
            <a class="btn btn-default btn-sm" href="{{ route('admin.products.index') }}" role="button">
                <span class="glyphicon glyphicon-remove do_nos"></span> Thoát
            </a>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box" id="view">
                    <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="category-name">Tên danh mục <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" id="category-name" name="name" value="{{ !empty($category) ? $category->name ?? old('name') : old('name') }}"
                                    placeholder="Nhập tên danh mục">
                                @error('name')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                                {{-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> --}}
                            </div>
                            <div class="form-group">
                                <label for="category-image">Ảnh danh mục <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="category-image" name="image">
                                        <label class="custom-file-label" for="category-image">{{ !empty($category) ? $category->image : 'Chọn ảnh danh mục' }}</label>
                                    </div>
                                </div>
                                @error('image')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label>Mô tả danh mục</label>
                                <textarea name="description" class="form-control" rows="5"
                                    placeholder="Nhập mô tả danh mục">{{ !empty($category) ? $category->description ?? old('description') : old('description') }}</textarea>
                            </div>
                        </div>
                    </div>
                </div><!-- /.box -->
            </div>
        </div>
    </section>
</form>

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('active-categories', 'active')
@section('breadcrumb', 'Thêm Danh Mục Mới')
@section('contents')
    @include('admin.categories._form')
@endsection
@section('custom-script')
    <!-- bs-custom-file-input -->
    <script src="{{ asset('adminlte/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
@endsection
@section('my-script')
    <script type="text/javascript">
        $(function() {
            bsCustomFileInput.init();
        });
    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('active-categories', 'active')
@section('breadcrumb', 'Chỉnh Sửa Danh Mục')
@section('contents')
    @include('admin.categories._form')
@endsection
@section('custom-script')
    <!-- bs-custom-file-input -->
    <script src="{{ asset('adminlte/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
@endsection
@section('my-script')
    <script type="text/javascript">
        $(function() {
            bsCustomFileInput.init();
        });
    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')
@section('custom-css')
    @include('admin.components.css.datatables')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/sweetalert2/sweetalert2.min.css') }}">
@endsection
@section('active-categories', 'active')
@section('breadcrumb', 'Danh Mục Sản Phẩm')
@section('contents')
    <div class="breadcrumb">
        <div class="">
        <a id=" btn-form-add" href="{{ route('admin.categories.create') }}"
            class="btn btn-primary btn-sm" role="button">
            <span class="glyphicon glyphicon-plus"></span>Thêm Mới
            </a>
        </div>
    </div>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="row row-table">
                    <div id="render-list-category" style="width: 98%;margin: auto;">
                        <div id="table-responsive1" class="table-responsive">
                            <table id="category-list" class="table table-hover table-bordered table-content">
                                <thead>
                                    <tr>
                                        <th class="text-center" width="5%">ID</th>
                                        <th class="text-center" width="15%">Tên Danh Mục</th>
                                        <th class="text-center" width="15%">Ảnh danh mục</th>
                                        <th class="text-center" width="20%">Mô Tả</th>
                                        <th class="text-center" width="15%">Thời gian tạo</th>
                                        <th class="text-center" width="20%">Thời gian chỉnh sửa gần nhất</th>
                                        <th class="text-center" width="10%">Thao Tác</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (!empty($categories))
                                        @foreach ($categories as $category)
                                            <tr>
                                                <td class="text-center">
                                                    {{ $category->id }}
                                                </td>
                                                <td class="text-center">
                                                    {{ $category->name }}
                                                </td>
                                                <td class="text-center">
                                                    <img style="width: 100px; max-height: 200px;"
                                                        src="{{ $category->image_path }}"
                                                        alt="{{ $category->image }}" />
                                                </td>
                                                <td class="text-center">
                                                    {{ $category->description }}
                                                </td>
                                                <td class="text-center">
                                                    {{ $category->created_at }}
                                                </td>
                                                <td class="text-center">
                                                    {{ $category->updated_at }}
                                                </td>
                                                <td class="text-center">
                                                    <a href="{{ route('admin.categories.edit', $category->id) }}"
                                                        type="button" class="btn btn-success btn-xs btn-edit-product">
                                                        <i class="fa fa-plus" aria-hidden="true"></i>Sửa
                                                    </a>
                                                    <form action="{{ route('admin.categories.destroy', $category->id) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button
                                                            type="submit"
                                                            data-url="{{ route('admin.categories.destroy', $category->id) }}"
                                                            class="btn btn-danger btn-xs btn-delete">
                                                            <i class="fa fa-trash" aria-hidden="true"></i>Xóa
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('custom-script')
    @include('admin.components.js.datatables')
    <script src="{{ asset('adminlte/plugins/sweetalert2/sweetalert2.all.min.js') }}"></script>
@endsection
@section('my-script')
    <script>
        $(function() {
            $('#category-list').DataTable({
                "paging": true,
                // "lengthChange": false,
                // "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });

            $('.btn-delete').click(function(e) {
                e.preventDefault();
                let url = $(this).attr('data-url');
                Swal.fire({
                    title: 'Bạn chắc chắn muốn xóa danh mục này?',
                    // text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCloseButton: true,
                    showCancelButton: true,
                    confirmButtonColor: '#42c119',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Xóa',
                    cancelButtonText: 'Hủy'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $(this).parent().submit()
                    }
                })
            });
        });
    </script>
@endsection